### ISSUE TITLE
Game crashe when use optimized mods

### ISSUE THREAD

**Issue by DaniloDaki648** [serpentspirale/Java-Mods-Optimizer#1]
Forge version: 1.12.2 - 14.23.5.2854
Mod used: Matterial Overdrive
When i use non optimized mod game work but when I exchange it for optimized game dont start
Can you help me? It would be good if i get it to work.
PS:no just MO every mod i use optimized game 
crash

**Comment by Mathias-Boulay** [comment]
@DaniloDaki648 didn't notice anyone posted an issue until now 😅 
Well, crashes have been reported since the tool is out.

For the Multi Optimization update, unzip and rezipping the whole archive should fix the problem but most issues should be fixed  in the next update 👍
